devguide:
  greeting: "안녕하세요. default account-service.yml !!"

---

spring:
  profiles: 
    active: stage
devguide:
  greeing: "스테이징! 안녕하세요!"

---

spring:
  profiles: 
    active: dev
devguide:
  greeing: "dev! 안녕하세요!"

---

spring:
  profiles: 
    active: local
devguide:
  greeing: "local! 안녕하세요!"